// Mocks generated by Mockito 5.4.4 from annotations
// in miyolist/test/core/services/conflict_resolver_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i14;

import 'package:hive_flutter/hive_flutter.dart' as _i2;
import 'package:miyolist/core/models/character_details.dart' as _i7;
import 'package:miyolist/core/models/media_details.dart' as _i6;
import 'package:miyolist/core/models/media_list_entry.dart' as _i5;
import 'package:miyolist/core/models/staff_details.dart' as _i8;
import 'package:miyolist/core/models/studio_details.dart' as _i9;
import 'package:miyolist/core/models/sync_conflict.dart' as _i12;
import 'package:miyolist/core/models/user_model.dart' as _i4;
import 'package:miyolist/core/models/user_settings.dart' as _i11;
import 'package:miyolist/core/services/crash_reporter.dart' as _i13;
import 'package:miyolist/core/services/local_storage_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i3.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<_i4.UserModel> get userBox => (super.noSuchMethod(
        Invocation.getter(#userBox),
        returnValue: _FakeBox_0<_i4.UserModel>(
          this,
          Invocation.getter(#userBox),
        ),
      ) as _i2.Box<_i4.UserModel>);

  @override
  _i2.Box<_i5.MediaListEntry> get animeListBox => (super.noSuchMethod(
        Invocation.getter(#animeListBox),
        returnValue: _FakeBox_0<_i5.MediaListEntry>(
          this,
          Invocation.getter(#animeListBox),
        ),
      ) as _i2.Box<_i5.MediaListEntry>);

  @override
  _i2.Box<_i5.MediaListEntry> get mangaListBox => (super.noSuchMethod(
        Invocation.getter(#mangaListBox),
        returnValue: _FakeBox_0<_i5.MediaListEntry>(
          this,
          Invocation.getter(#mangaListBox),
        ),
      ) as _i2.Box<_i5.MediaListEntry>);

  @override
  _i2.Box<dynamic> get favoritesBox => (super.noSuchMethod(
        Invocation.getter(#favoritesBox),
        returnValue: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#favoritesBox),
        ),
      ) as _i2.Box<dynamic>);

  @override
  _i2.Box<dynamic> get settingsBox => (super.noSuchMethod(
        Invocation.getter(#settingsBox),
        returnValue: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#settingsBox),
        ),
      ) as _i2.Box<dynamic>);

  @override
  _i2.Box<_i6.MediaDetails> get mediaCacheBox => (super.noSuchMethod(
        Invocation.getter(#mediaCacheBox),
        returnValue: _FakeBox_0<_i6.MediaDetails>(
          this,
          Invocation.getter(#mediaCacheBox),
        ),
      ) as _i2.Box<_i6.MediaDetails>);

  @override
  _i2.Box<_i7.CharacterDetails> get characterCacheBox => (super.noSuchMethod(
        Invocation.getter(#characterCacheBox),
        returnValue: _FakeBox_0<_i7.CharacterDetails>(
          this,
          Invocation.getter(#characterCacheBox),
        ),
      ) as _i2.Box<_i7.CharacterDetails>);

  @override
  _i2.Box<_i8.StaffDetails> get staffCacheBox => (super.noSuchMethod(
        Invocation.getter(#staffCacheBox),
        returnValue: _FakeBox_0<_i8.StaffDetails>(
          this,
          Invocation.getter(#staffCacheBox),
        ),
      ) as _i2.Box<_i8.StaffDetails>);

  @override
  _i2.Box<_i9.StudioDetails> get studioCacheBox => (super.noSuchMethod(
        Invocation.getter(#studioCacheBox),
        returnValue: _FakeBox_0<_i9.StudioDetails>(
          this,
          Invocation.getter(#studioCacheBox),
        ),
      ) as _i2.Box<_i9.StudioDetails>);

  @override
  _i10.Future<void> saveUser(_i4.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveAnimeList(List<_i5.MediaListEntry>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnimeList,
          [entries],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<_i5.MediaListEntry> getAnimeList() => (super.noSuchMethod(
        Invocation.method(
          #getAnimeList,
          [],
        ),
        returnValue: <_i5.MediaListEntry>[],
      ) as List<_i5.MediaListEntry>);

  @override
  _i10.Future<void> saveMangaList(List<_i5.MediaListEntry>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMangaList,
          [entries],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<_i5.MediaListEntry> getMangaList() => (super.noSuchMethod(
        Invocation.method(
          #getMangaList,
          [],
        ),
        returnValue: <_i5.MediaListEntry>[],
      ) as List<_i5.MediaListEntry>);

  @override
  _i10.Future<void> updateAnimeEntry(_i5.MediaListEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAnimeEntry,
          [entry],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateMangaEntry(_i5.MediaListEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMangaEntry,
          [entry],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAnimeEntry(int? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAnimeEntry,
          [entryId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteMangaEntry(int? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMangaEntry,
          [entryId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveFavorites(Map<String, dynamic>? favorites) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFavorites,
          [favorites],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveLastSyncTime(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #saveLastSyncTime,
          [time],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveUserSettings(_i11.UserSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserSettings,
          [settings],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool isPublicProfile() => (super.noSuchMethod(
        Invocation.method(
          #isPublicProfile,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isCloudSyncEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isCloudSyncEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> saveConflictResolutionStrategy(
          _i12.ConflictResolutionStrategy? strategy) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConflictResolutionStrategy,
          [strategy],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveMediaDetails(_i6.MediaDetails? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMediaDetails,
          [media],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i6.MediaDetails? getMediaDetails(int? mediaId) =>
      (super.noSuchMethod(Invocation.method(
        #getMediaDetails,
        [mediaId],
      )) as _i6.MediaDetails?);

  @override
  List<_i6.MediaDetails> getAllCachedMedia() => (super.noSuchMethod(
        Invocation.method(
          #getAllCachedMedia,
          [],
        ),
        returnValue: <_i6.MediaDetails>[],
      ) as List<_i6.MediaDetails>);

  @override
  _i10.Future<void> saveCharacterDetails(_i7.CharacterDetails? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCharacterDetails,
          [character],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i7.CharacterDetails? getCharacterDetails(int? characterId) =>
      (super.noSuchMethod(Invocation.method(
        #getCharacterDetails,
        [characterId],
      )) as _i7.CharacterDetails?);

  @override
  List<_i7.CharacterDetails> getAllCachedCharacters() => (super.noSuchMethod(
        Invocation.method(
          #getAllCachedCharacters,
          [],
        ),
        returnValue: <_i7.CharacterDetails>[],
      ) as List<_i7.CharacterDetails>);

  @override
  _i10.Future<void> saveStaffDetails(_i8.StaffDetails? staff) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStaffDetails,
          [staff],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i8.StaffDetails? getStaffDetails(int? staffId) =>
      (super.noSuchMethod(Invocation.method(
        #getStaffDetails,
        [staffId],
      )) as _i8.StaffDetails?);

  @override
  List<_i8.StaffDetails> getAllCachedStaff() => (super.noSuchMethod(
        Invocation.method(
          #getAllCachedStaff,
          [],
        ),
        returnValue: <_i8.StaffDetails>[],
      ) as List<_i8.StaffDetails>);

  @override
  _i10.Future<void> saveStudioDetails(_i9.StudioDetails? studio) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStudioDetails,
          [studio],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i9.StudioDetails? getStudioDetails(int? studioId) =>
      (super.noSuchMethod(Invocation.method(
        #getStudioDetails,
        [studioId],
      )) as _i9.StudioDetails?);

  @override
  List<_i9.StudioDetails> getAllCachedStudios() => (super.noSuchMethod(
        Invocation.method(
          #getAllCachedStudios,
          [],
        ),
        returnValue: <_i9.StudioDetails>[],
      ) as List<_i9.StudioDetails>);

  @override
  _i10.Future<void> clearExpiredCache(
          {Duration? maxAge = const Duration(days: 7)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearExpiredCache,
          [],
          {#maxAge: maxAge},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> getDatabaseSizeInBytes() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseSizeInBytes,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<double> getDatabaseSizeInMB() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseSizeInMB,
          [],
        ),
        returnValue: _i10.Future<double>.value(0.0),
      ) as _i10.Future<double>);

  @override
  _i10.Future<Map<String, dynamic>> getDatabaseStats() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseStats,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<bool> isDatabaseSizeExceeded() => (super.noSuchMethod(
        Invocation.method(
          #isDatabaseSizeExceeded,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> enforceSizeLimit() => (super.noSuchMethod(
        Invocation.method(
          #enforceSizeLimit,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [CrashReporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashReporter extends _i1.Mock implements _i13.CrashReporter {
  MockCrashReporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> didCrashInLastSession() => (super.noSuchMethod(
        Invocation.method(
          #didCrashInLastSession,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<String?> getLastCrashReport() => (super.noSuchMethod(
        Invocation.method(
          #getLastCrashReport,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> markSessionStart() => (super.noSuchMethod(
        Invocation.method(
          #markSessionStart,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> markGracefulShutdown() => (super.noSuchMethod(
        Invocation.method(
          #markGracefulShutdown,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> log(
    String? message, {
    _i13.LogLevel? level = _i13.LogLevel.debug,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {
            #level: level,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i14.File>> getAllLogFiles() => (super.noSuchMethod(
        Invocation.method(
          #getAllLogFiles,
          [],
        ),
        returnValue: _i10.Future<List<_i14.File>>.value(<_i14.File>[]),
      ) as _i10.Future<List<_i14.File>>);

  @override
  _i10.Future<void> clearLogs() => (super.noSuchMethod(
        Invocation.method(
          #clearLogs,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> getLogsDirectory() => (super.noSuchMethod(
        Invocation.method(
          #getLogsDirectory,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getLogsDirectory,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> getCurrentSessionLogs() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSessionLogs,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentSessionLogs,
            [],
          ),
        )),
      ) as _i10.Future<String>);
}
